title: Daniela (Dana) Valentina Vioreanu
logo: assets/headshot.png
description1: I help companies clarify their brand message & stories
description2: English translator
show_downloads: true
theme: jekyll-theme-minimal
