title: Daniela (Dana) Valentina Vioreanu
logo: assets/headshot.png
description: I help companies clarify their brand message & stories<br>
English translator<br>
show_downloads: true
theme: jekyll-theme-minimal
