title: Daniela (Dana) Valentina Vioreanu
logo: assets/headshot.png
description: English translator helping companies clarify their brand message & stories
show_downloads: true
theme: jekyll-theme-minimal
